function [fitresult, gof] = createFit(Xreg, Yreg)
%CREATEFIT(XREG,YREG)
%  Create a fit.
%
%  Data for 'AjusteExperimentos' fit:
%      X Input : Xreg
%      Y Output: Yreg
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Jan-2019 23:46:54


%% Fit: 'AjusteExperimentos'.
[xData, yData] = prepareCurveData( Xreg, Yreg );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'AjusteExperimentos' );
h = plot( fitresult, xData, yData );
legend( h, 'Yreg vs. Xreg', 'AjusteExperimentos', 'Location', 'NorthEast' );
% Label axes
xlabel Xreg
ylabel Yreg
grid on


